sudo: false
dist: trusty
language: java
jdk:
  - openjdk8

before_script:
  - wget https://github.com/vufind-org/vufind/archive/v3.1.3.zip
  - unzip v3.1.3.zip

script:
  - ant test -Dvufind.dir=vufind-3.1.3
